export interface ProjectPath {
    path: string;
    label?: string;
}

export interface ProjectScan {
    pattern: string;
    options?: {
        limit?: number;
        exclude?: string[];
    };
}

/** How a project's baseline advances between runs. Absent means `approved`. */
export type BaselinePolicy = 'approved' | 'rolling';

/** Frequency at which a project runs unattended. */
export type ProjectSchedule = 'hourly' | 'daily' | 'weekly';

export interface ProjectConfig {
    name: string;
    testOrigin?: string;
    baseOrigin?: string;
    sitemapUrl?: string;
    paths?: ProjectPath[];
    scans?: ProjectScan[];
    devices?: string[];
    masks?: string[];
    /** CSS injected before screenshotting, to hide dynamic widgets. Max 4096 characters. */
    customCss?: string;
    concurrency?: number;
    createdAt?: string;
    updatedAt?: string;
    lastRunAt?: string;
    lastJobId?: string;
    baselineInvalidatedAt?: string;
    baselineVersion?: string;
    /**
     * `approved` (default): a person accepts a run and its captures become the baseline.
     * `rolling`: every completed managed run advances it, and those runs auto-approve.
     * Changing this does not invalidate baselines.
     */
    baselinePolicy?: BaselinePolicy;
    /**
     * Run this project unattended at this frequency. Requires `baselinePolicy: 'rolling'`
     * on a managed project — the API rejects the combination without it. Pass `null` via
     * updateProject() to remove the schedule.
     */
    schedule?: ProjectSchedule | null;
    /**
     * The API key recorded when the schedule was set; every scheduled run is attributed
     * to it. Absent if the schedule was set without an API key, in which case AI
     * summaries are skipped for those runs.
     */
    scheduleKeyId?: string;
    /** When the scheduler last started a run. The next run is due one interval after this. */
    lastScheduledRunAt?: string;
}

export interface VRConfig {
    apiKey?: string;
    apiUrl?: string;
}

export interface Viewport {
    width: number;
    height: number;
}

export const Viewports = {
    DESKTOP: { width: 1920, height: 1080 },
    LAPTOP: { width: 1366, height: 768 },
    TABLET: { width: 768, height: 1024 },
    MOBILE: { width: 375, height: 667 }
} as const;

export interface RegionVerdict {
    decision: 'intentional' | 'bug' | 'noise' | 'needs_review';
    confidence: number;
    reasoning: string;
}

/** Rolled-up verdict for one URL + device result, plus the per-region verdicts behind it. */
export interface ResultVerdict {
    decision: 'intentional' | 'bug' | 'noise' | 'needs_review';
    minConfidence: number;
    avgConfidence: number;
    /** Keyed by region label (A, B, C…). */
    regions: Record<string, RegionVerdict>;
}

export interface RegressionbotSummaryItem {
    label: string;
    text: string;
    verdict?: RegionVerdict;
}

/**
 * Result for a single URL + device comparison.
 *
 * Returned by both getStatus() and getSummary(). Pre-signed image URLs
 * (baselineUrl, currentUrl, diffUrl) are only populated by getSummary() —
 * they are absent when reading results from getStatus().
 */
export interface PageResult {
    url: string;
    /** Device variant tested (e.g. "desktop_chrome", "iphone_12"). */
    variantName: string;
    /** Percentage of pixels that differed from the baseline (0 = identical). */
    diffPercentage: number;
    /** Raw count of differing pixels. */
    diffCount: number;
    /** Perceptual similarity 0-100 (SSIM). */
    visualMatchScore: number;
    /** Plain-English description of what visually changed, generated by RegressionBot. */
    regressionbotSummary?: RegressionbotSummaryItem[];
    /** Whether the change was judged intentional, a bug, or noise. Present once verdicts have run. */
    verdict?: ResultVerdict;
    /** Pre-signed URL for the stored baseline screenshot. */
    baselineUrl?: string;
    /** Pre-signed URL for the newly captured screenshot. */
    currentUrl?: string;
    /** Pre-signed URL for the side-by-side annotated diff image. */
    diffUrl?: string;
}

export interface JobProgress {
    total: number;
    completed: number;
    percent: string;
}

export interface JobStatus {
    jobId: string;
    status: 'INITIALIZING' | 'PROCESSING' | 'FINISHING' | 'SUMMARIZING' | 'COMPLETED' | 'APPROVED' | 'FAILED';
    summaryStatus?: 'PENDING' | 'PROCESSING' | 'COMPLETE';
    error?: string;
    progress?: JobProgress;
    executionTime?: number;
    createdAt?: string;
    /** Partial or complete results. Present once workers start completing. Pre-signed image URLs are not included — call getSummary() for those. */
    results?: PageResult[];
}

export interface JobSummary {
    jobId: string;
    status: string;
    summaryStatus?: 'PENDING' | 'PROCESSING' | 'COMPLETE';
    error?: string | null;
    totalUrls: number;
    completedCount: number;
    /** Overall quality score 0–100 across all tested pages. */
    overallScore: number;
    executionTime: number;
    regressionCount: number;
    matchCount: number;
    newBaselineCount: number;
    errorCount: number;
    /** Pages where a visual regression was detected. Includes pre-signed image URLs. */
    regressions: PageResult[];
    /** Pages that matched the baseline. Includes pre-signed image URLs. */
    matches: PageResult[];
    /** Pages captured for the first time — no baseline existed to compare against. */
    newBaselines: Array<{ url: string; variantName: string }>;
    /** Pages that failed to capture or compare. */
    errors: Array<{ url: string; variantName: string; errorMessage: string }>;
    intentAssessment?: IntentAssessment;
    runContext?: RunContext;
}

export interface RunContext {
    changeDescription?: string;
    gitCommitSha?: string;
    gitCommitMessage?: string;
    prTitle?: string;
    prDescription?: string;
    expectedChanges?: string[];
    scope?: string[];
}

export interface IntentAssessment {
    intentProvided: boolean;
    bugCount: number;
    intentionalCount: number;
    noiseCount: number;
    needsReviewCount: number;
    allAccountedFor: boolean;
    summary: string;
}

export interface JobAiSummary {
    message: string;
    jobId: string;
    summaries: Array<{
        url: string;
        variantName: string;
        regressionbotSummary: RegressionbotSummaryItem[];
    }>;
}

